version: "2"
services:

  db:
    container_name: crm-db
    image: microsoft/mssql-server-linux
    #restart: always 
    ports: 
      - 1433:1433
    environment:
      SA_PASSWORD: SQL_DB_CRM@123*
      MSSQL_DB: Stark-CRM
    networks:
      app_net:
        ipv4_address: 10.1.23.2

  web:
    container_name: CRM-module-itg
    build: .
    ports:
      - 8835:8080
    networks:
      app_net:
        ipv4_address: 10.1.23.3
    links:
      - db
    environment:
      CATALINA_OPTS: -Dspring.config.location=/usr/local/tomcat/application.properties

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.23.0/24
        gateway: 10.1.23.1